[package]
name = "intro"
version = "0.1.0"
authors = ["Loic Roux <loic.roux.404@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
